VALUE_MODIFIER_DB_PATH = "scripts/value_modifier.db"
FILTERS = {
    "YEAR" :2024,
    "MONTH" : 11
}
INSTRUMENTS = {
    "MEAN": "INSTRUMENT1",
    "MEAN_DATE": "INSTRUMENT2",
    "STDDEV": "INSTRUMENT3"
}
TOP_N = 10